import './common.sass';
import './vars.sass';
import './layout.sass';
import ReduxProvider from './ReduxProvider';

export const metadata = {
  title: 'Game',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={`layout`}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
