import './common.sass';
import './vars.sass';
import './layout.sass';

export const metadata = {
  title: 'Game',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={`layout`}>{children}</body>
    </html>
  );
}
